from config.constants import (
    MAX_RAW_CONFIG_BYTES,
    RATE_LIMIT_BURST,
    RATE_LIMIT_REQUESTS_PER_MINUTE,
)

BRIDGE_TOKEN_VERSION = "v1"
BRIDGE_TOKEN_TTL_SECONDS = 900  # 15 minutes
BRIDGE_TOKEN_MAX_FUTURE_SKEW_SECONDS = 30
MAX_BRIDGE_REQUEST_TARGET_BYTES = 2048

__all__ = [
    "BRIDGE_TOKEN_MAX_FUTURE_SKEW_SECONDS",
    "BRIDGE_TOKEN_TTL_SECONDS",
    "BRIDGE_TOKEN_VERSION",
    "MAX_BRIDGE_REQUEST_TARGET_BYTES",
    "MAX_RAW_CONFIG_BYTES",
    "RATE_LIMIT_BURST",
    "RATE_LIMIT_REQUESTS_PER_MINUTE",
]
