FROM postgres:16.15-alpine@sha256:cf78e76683b9ca8c5733cbbdce6c9262b45b6767934dd0a95e671f9a0fc20685

RUN apk add --no-cache age bash curl

COPY scripts/docker/backup.sh /backup.sh
RUN chmod 0755 /backup.sh

ENTRYPOINT ["/bin/bash", "/backup.sh"]
