FROM postgres:18.6-alpine@sha256:d3e1620b530c944afa6e887d22eb899824da68e19c52024bf98f5220c88a65b2

RUN apk add --no-cache age bash curl

COPY scripts/docker/backup.sh /backup.sh
RUN chmod 0755 /backup.sh

ENTRYPOINT ["/bin/bash", "/backup.sh"]
