FROM postgres:16.14-alpine@sha256:57c72fd2a128e416c7fcc499958864df5301e940bca0a56f58fddf30ffc07777

RUN (echo "https://dl-cdn.alpinelinux.org/alpine/v3.20/main" > /etc/apk/repositories && \
     echo "https://dl-cdn.alpinelinux.org/alpine/v3.20/community" >> /etc/apk/repositories && \
     echo "https://uk.alpinelinux.org/alpine/v3.20/main" >> /etc/apk/repositories && \
     echo "https://uk.alpinelinux.org/alpine/v3.20/community" >> /etc/apk/repositories) && \
    apk add --no-cache --network-timeout 10 age bash curl

COPY scripts/docker/backup.sh /backup.sh
RUN chmod 0755 /backup.sh

ENTRYPOINT ["/bin/bash", "/backup.sh"]
