import re

content = open("bot/texts_data/overrides.py", "r", encoding="utf-8").read()

replacements = {
    "ADMIN_BAN_CONFIRM": "Вы уверены, что хотите забанить пользователя?",
    "ADMIN_BAN_FAILED": "❌ Ошибка при попытке забанить пользователя.",
    "ADMIN_BAN_SUCCESS": "✅ Пользователь успешно забанен.",
    "ADMIN_DELETE_DEVICE_CONFIRM": "Вы уверены, что хотите удалить устройство?",
    "ADMIN_DELETE_DEVICE_ERROR": "❌ Произошла ошибка при удалении устройства.",
    "ADMIN_DELETE_DEVICE_FAILED": "❌ Не удалось удалить устройство.",
    "ADMIN_DELETE_DEVICE_SUCCESS": "✅ Устройство успешно удалено.",
    "ADMIN_MANUAL_GRANT_USER_BANNED": "❌ Невозможно выдать подписку: пользователь забанен.",
    "ADMIN_MANUAL_GRANT_USER_DELETED": "❌ Невозможно выдать подписку: пользователь удален.",
    "ADMIN_SERVER_ADDED": "✅ Сервер успешно добавлен.",
    "ADMIN_SERVER_CARD": "🖥 <b>Сервер:</b> {server_name}\\nURL: {server_url}\\nМакс. клиентов: {max_clients}",
    "ADMIN_SERVER_CHECKING": "🔄 Проверка сервера...",
    "ADMIN_SERVER_DELETE_CONFIRM": "Вы уверены, что хотите удалить этот сервер?",
    "ADMIN_SERVER_EDIT_KEY_PROMPT": "Введите новый ключ для сервера:",
    "ADMIN_SERVER_EDIT_MAX_CLIENTS_PROMPT": "Введите максимальное количество клиентов для сервера:",
    "ADMIN_SERVER_EDIT_URL_PROMPT": "Введите новый URL сервера:",
    "ADMIN_SERVER_FLAG_PROMPT": "Выберите флаг для сервера:",
    "ADMIN_SERVER_FLAG_PROMPT_EDIT": "Выберите новый флаг для сервера:",
    "ADMIN_SERVER_FLAG_TOO_LONG": "❌ Флаг слишком длинный.",
    "ADMIN_SERVER_FLAG_UPDATED": "✅ Флаг сервера обновлен.",
    "ADMIN_SERVER_KEY_PROMPT": "Введите ключ доступа:",
    "ADMIN_SERVER_KEY_UPDATED": "✅ Ключ сервера обновлен.",
    "ADMIN_SERVER_MAX_CLIENTS_UPDATED": "✅ Макс. количество клиентов обновлено.",
    "ADMIN_SERVER_MAX_CLIENTS_WARNING": "⚠️ Внимание: на сервере уже больше клиентов, чем новый лимит.",
    "ADMIN_SERVER_NAME_PROMPT": "Введите название сервера:",
    "ADMIN_SERVER_RENAMED": "✅ Сервер успешно переименован.",
    "ADMIN_SERVER_RENAME_PROMPT": "Введите новое имя сервера:",
    "ADMIN_SERVER_STATE_DISABLED": "🔴 Отключен",
    "ADMIN_SERVER_STATE_ENABLED": "🟢 Включен",
    "ADMIN_SERVER_TOGGLE_DISABLE_CONFIRM": "Вы уверены, что хотите отключить сервер?",
    "ADMIN_SERVER_TOGGLE_ENABLE_CONFIRM": "Вы уверены, что хотите включить сервер?",
    "ADMIN_SERVER_TOGGLE_SUCCESS": "✅ Статус сервера изменен.",
    "ADMIN_SERVER_URL_UPDATED": "✅ URL сервера обновлен.",
    "ADMIN_SUBSCRIPTION_HEADER": "💳 Управление подпиской пользователя",
    "ADMIN_SUB_CHANGE_FAILED": "❌ Ошибка при изменении подписки.",
    "ADMIN_SUB_CHANGE_TARIFF_HEADER": "Выберите новый тариф:",
    "ADMIN_SUB_CONFIRM_EXTEND": "Вы уверены, что хотите продлить подписку?",
    "ADMIN_SUB_CONFIRM_GRANT": "Вы уверены, что хотите выдать подписку?",
    "ADMIN_SUB_CONFIRM_REDUCE": "Вы уверены, что хотите сократить подписку?",
    "ADMIN_SUB_CONFIRM_TARIFF": "Вы уверены, что хотите сменить тариф?",
    "ADMIN_SUB_DOWNGRADE_BLOCKED": "❌ Нельзя понизить тариф (превышен лимит устройств).",
    "ADMIN_SUB_EXTEND_FAILED": "❌ Не удалось продлить подписку.",
    "ADMIN_SUB_EXTEND_HEADER": "Продление подписки",
    "ADMIN_SUB_EXTEND_PROMPT": "На сколько дней продлить подписку?",
    "ADMIN_SUB_EXTEND_SUCCESS": "✅ Подписка успешно продлена.",
    "ADMIN_SUB_GRANT_CUSTOM_PROMPT": "Введите количество дней:",
    "ADMIN_SUB_GRANT_DAYS_HEADER": "На какой срок выдать подписку?",
    "ADMIN_SUB_GRANT_FAILED": "❌ Ошибка при выдаче подписки.",
    "ADMIN_SUB_GRANT_HEADER": "Выдача новой подписки",
    "ADMIN_SUB_GRANT_SUCCESS": "✅ Подписка успешно выдана.",
    "ADMIN_SUB_GROUP_NOT_FOUND": "❌ Группа тарифов не найдена.",
    "ADMIN_SUB_NO_SUBSCRIPTION": "У пользователя нет активной подписки.",
    "ADMIN_SUB_PERMANENT_LABEL": "Навсегда",
    "ADMIN_SUB_REDUCED": "✅ Подписка успешно сокращена.",
    "ADMIN_SUB_REDUCE_FAILED": "❌ Не удалось сократить подписку.",
    "ADMIN_SUB_REDUCE_PROMPT": "На сколько дней сократить подписку?",
    "ADMIN_SUB_STATUS_ACTIVE": "Активна",
    "ADMIN_SUB_STATUS_INACTIVE": "Неактивна",
    "ADMIN_SUB_STATUS_NONE": "Отсутствует",
    "ADMIN_SUB_TARIFF_ALREADY_SELECTED": "❌ Этот тариф уже активен.",
    "ADMIN_SUB_TARIFF_CHANGED": "✅ Тариф успешно изменен.",
    "ADMIN_TARIFF_EDIT_RUB_PROMPT": "Введите новую цену в рублях:",
    "ADMIN_TARIFF_EDIT_RUB_SUCCESS": "✅ Цена тарифа успешно обновлена.",
    "ADMIN_TARIFF_TOGGLE_BLOCKED_PENDING": "❌ Нельзя отключить тариф, есть незавершенные платежи.",
    "ADMIN_TARIFF_TOGGLE_SUCCESS_DISABLED": "✅ Тариф отключен.",
    "ADMIN_TARIFF_TOGGLE_SUCCESS_ENABLED": "✅ Тариф включен.",
    "ADMIN_UNBAN_CONFIRM": "Вы уверены, что хотите разбанить пользователя?",
    "ADMIN_USER_DEVICES_EMPTY": "Нет подключенных устройств.",
    "ADMIN_USER_DEVICES_HEADER": "📱 Устройства пользователя",
    "ALERT_CRITICAL_BOT_ERROR": "❌ Произошла критическая ошибка бота.",
    "ERROR_SERVER_DUPLICATE_URL": "❌ Сервер с таким URL уже существует.",
    "ADMIN_PAYMENT_USER_WITH_USERNAME": "@{username}",
    "ADMIN_PAYMENT_USER_WITH_ID": "ID: {user_id}"
}

for k, v in replacements.items():
    content = re.sub(
        rf"OVERRIDES\['{k}'\] = '\[MISSING TEXT: {k}\]'", 
        f"OVERRIDES['{k}'] = '{v}'", 
        content
    )

with open("bot/texts_data/overrides.py", "w", encoding="utf-8") as f:
    f.write(content)

print("Replaced successfully!")
