"""Constants for Amnezia 1-Click Web Bridge."""

BRIDGE_TOKEN_VERSION = "v1"
BRIDGE_TOKEN_TTL_SECONDS = 900  # 15 minutes
BRIDGE_TOKEN_MAX_FUTURE_SKEW_SECONDS = 30
MAX_BRIDGE_REQUEST_TARGET_BYTES = 2048
MAX_RAW_CONFIG_BYTES = 65536  # 64 KiB
RATE_LIMIT_REQUESTS_PER_MINUTE = 30.0
RATE_LIMIT_BURST = 10
