"""Domain package bot.texts.user."""
from __future__ import annotations

from bot.texts.user.hub import (
    BOT_START_DESCRIPTION,
    CURRENCY_RUB_SYMBOL,
    HUB_HEADER,
    PAYMENT_STATUS_PENDING_ICON,
    USER_HUB_START,
)

from bot.texts.user.onboarding import (
    START_REGISTERED,
    WELCOME_TEXT,
)

from bot.texts.user.referral import (
    REFERRAL_LIST_EMPTY,
    REFERRAL_LIST_FOOTER,
    REFERRAL_LIST_HEADER,
    REFERRAL_SHARE_TEXT,
    REFERRAL_TEXT_BALANCE,
)

from bot.texts.user.support import (
    BTN_PRIVACY_POLICY,
    BTN_TOS,
    FAQ_TEXT,
    PRIVACY_POLICY_URL,
    SUPPORT,
    SUPPORT_DOWNLOAD_CLIENT_TEXT,
    SUPPORT_GREETING_TEMPLATE,
    SUPPORT_HELP_ROOT_TEXT,
    SUPPORT_IOS_INSTRUCTION_TEXT,
    SUPPORT_SPLIT_TUNNELING_TEXT,
    SUPPORT_TEXT,
    SUPPORT_WINDOWS_INSTRUCTION_TEXT,
    TOS_AGREEMENT_URL,
)

__all__ = [
    "BOT_START_DESCRIPTION",
    "BTN_PRIVACY_POLICY",
    "BTN_TOS",
    "CURRENCY_RUB_SYMBOL",
    "FAQ_TEXT",
    "HUB_HEADER",
    "PAYMENT_STATUS_PENDING_ICON",
    "PRIVACY_POLICY_URL",
    "REFERRAL_LIST_EMPTY",
    "REFERRAL_LIST_FOOTER",
    "REFERRAL_LIST_HEADER",
    "REFERRAL_SHARE_TEXT",
    "REFERRAL_TEXT_BALANCE",
    "START_REGISTERED",
    "SUPPORT",
    "SUPPORT_DOWNLOAD_CLIENT_TEXT",
    "SUPPORT_GREETING_TEMPLATE",
    "SUPPORT_HELP_ROOT_TEXT",
    "SUPPORT_IOS_INSTRUCTION_TEXT",
    "SUPPORT_SPLIT_TUNNELING_TEXT",
    "SUPPORT_TEXT",
    "SUPPORT_WINDOWS_INSTRUCTION_TEXT",
    "TOS_AGREEMENT_URL",
    "USER_HUB_START",
    "WELCOME_TEXT",
]
