"""Domain package bot.texts.user."""
from __future__ import annotations

from bot.texts.user.hub import (
    BOT_START_DESCRIPTION,
    CURRENCY_RUB_SYMBOL,
    HUB_BONUS_LINE_FORMAT,
    HUB_HEADER,
    PAYMENT_STATUS_PENDING_ICON,
    USER_HUB_START,
)

from bot.texts.user.onboarding import (
    WELCOME_TEXT,
)

from bot.texts.user.referral import (
    REFERRAL_LIST_EMPTY,
    REFERRAL_LIST_FOOTER,
    REFERRAL_LIST_HEADER,
    REFERRAL_LIST_ITEM_FORMAT,
    REFERRAL_SHARE_TEXT,
    REFERRAL_TEXT_BALANCE,
    REFERRAL_TOPUP_NOTIFY_TEMPLATE,
)

from bot.texts.user.support import (
    AMNEZIA_DOCS,
    AMNEZIA_DOWNLOAD_MIRROR,
    AMNEZIA_GITHUB_LATEST,
    AMNEZIA_IOS_RU,
    AMNEZIA_OFFICIAL_SITE,
    AMNEZIA_SPLIT_TUNNELING,
    AMNEZIA_WIN_INSTALL,
    AMNEZIA_WIN_UPDATE,
    BTN_PRIVACY_POLICY,
    BTN_TOS,
    FAQ_TEXT,
    PRIVACY_POLICY_URL,
    SUPPORT,
    SUPPORT_DOWNLOAD_CLIENT_TEXT,
    SUPPORT_GREETING_TEMPLATE,
    SUPPORT_HELP_ROOT_TEXT,
    SUPPORT_IOS_INSTRUCTION_TEXT,
    SUPPORT_SPLIT_TUNNELING_TEXT,
    SUPPORT_TEXT,
    SUPPORT_WINDOWS_INSTRUCTION_TEXT,
    TOS_AGREEMENT_URL,
)

__all__ = [
    "AMNEZIA_DOCS",
    "AMNEZIA_DOWNLOAD_MIRROR",
    "AMNEZIA_GITHUB_LATEST",
    "AMNEZIA_IOS_RU",
    "AMNEZIA_OFFICIAL_SITE",
    "AMNEZIA_SPLIT_TUNNELING",
    "AMNEZIA_WIN_INSTALL",
    "AMNEZIA_WIN_UPDATE",
    "BOT_START_DESCRIPTION",
    "BTN_PRIVACY_POLICY",
    "BTN_TOS",
    "CURRENCY_RUB_SYMBOL",
    "FAQ_TEXT",
    "HUB_BONUS_LINE_FORMAT",
    "HUB_HEADER",
    "PAYMENT_STATUS_PENDING_ICON",
    "PRIVACY_POLICY_URL",
    "REFERRAL_LIST_EMPTY",
    "REFERRAL_LIST_FOOTER",
    "REFERRAL_LIST_HEADER",
    "REFERRAL_LIST_ITEM_FORMAT",
    "REFERRAL_SHARE_TEXT",
    "REFERRAL_TEXT_BALANCE",
    "REFERRAL_TOPUP_NOTIFY_TEMPLATE",
    "SUPPORT",
    "SUPPORT_DOWNLOAD_CLIENT_TEXT",
    "SUPPORT_GREETING_TEMPLATE",
    "SUPPORT_HELP_ROOT_TEXT",
    "SUPPORT_IOS_INSTRUCTION_TEXT",
    "SUPPORT_SPLIT_TUNNELING_TEXT",
    "SUPPORT_TEXT",
    "SUPPORT_WINDOWS_INSTRUCTION_TEXT",
    "TOS_AGREEMENT_URL",
    "USER_HUB_START",
    "WELCOME_TEXT",
]
