"""Domain copy catalogue for: common/buttons.py"""

TEXTS = {
    'BTN_BUY_SUBSCRIPTION': '🛒 Купить подписку',
    'BTN_CANCEL': '❌ Отмена',
    'BTN_MY_BALANCE': '🎁 Мой баланс',
    'UI_SERVICES_WORKERS_ACCOUNT_BALANCE_L287_1': '🎁 Мой баланс',
    'BTN_HIDE': '✖ Скрыть',
    'BTN_MAIN_MENU': '🏠 В главное меню',
    'BTN_PAGINATION_NEXT': 'Вперед ▶️',
    'BTN_PAGINATION_PREV': '◀️ Назад',
    'BTN_READ_DISMISS': '✅ Прочитано',
    'BUTTON_BACK': '← Назад',
    'BUTTON_CHECK_TOPUP': '🔄 Проверить статус',
    'BUTTON_CLOSE_TOPUP': '🗂 Закрыть эту ссылку',
    'BUTTON_COPY_REFERRAL': '📋 Скопировать ссылку',
    'BUTTON_CUSTOM_AMOUNT': 'Другая сумма',
    'BUTTON_MAIN_MENU': '🏠 В главное меню',
    'BUTTON_REFERRAL_LIST': '👥 Список рефералов',
    'BUTTON_RESUME_TOPUP': '💳 Продолжить пополнение',
    'BUTTON_TOPUP': '➕ Пополнить баланс',
    'RUNTIME_BOT_KEYBOARDS_COMMON_L63_1': '← В главное меню',
    'RUNTIME_BOT_KEYBOARDS_COMMON_L65_1': '← Назад',
    'UI_BOT_KEYBOARDS_ADMIN_DASHBOARD_L80_1': '✅ Подтвердить',
    'UI_BOT_KEYBOARDS_ADMIN_DASHBOARD_L84_1': '❌ Отмена',
    'UI_BOT_KEYBOARDS_COMMON_L13_1': '⏳ Моя подписка',
    'UI_BOT_KEYBOARDS_COMMON_L18_1': '🚀 Купить доступ',
    'UI_BOT_KEYBOARDS_COMMON_L23_1': '🔌 Подключения',
    'UI_BOT_KEYBOARDS_COMMON_L28_1': '💰 Баланс',
    'UI_BOT_KEYBOARDS_COMMON_L38_1': '💬 Поддержка',
    'UI_BOT_KEYBOARDS_COMMON_L44_1': '🛠 Админка',
}
