
UI_FORMATTERS_AKTIVEN_55 = '🟢 Активен'
UI_FORMATTERS_NEAKTIVEN_55 = '🔴 Неактивен'
UI_FORMATTERS_ZABANEN_56 = '🚫 ЗАБАНЕН'
UI_FORMATTERS_NE_ZABANEN_56 = '✅ Не забанен'
UI_FORMATTERS_DN_155 = '{v} дн.'
UI_FORMATTERS_DA_157 = 'Да'
UI_FORMATTERS_NET_157 = 'Нет'
UI_FORMATTERS_ADMINKA_202 = '🏠 Админка'
