# Точечные переопределения текстов.
# Применяются после user_texts и admin_texts.

OVERRIDES = {
    "ADMIN_SERVER_URL_PROMPT": (
        "🔗 Введите API URL сервера "
        "(например: https://api.example.com:8443):"
    ),

    "ERROR_INVALID_URL": """⚠️ Некорректный формат URL.

URL должен начинаться с <code>https://</code>

Пример: <code>https://api.example.com:8443</code>""",
}

OVERRIDES['ADMIN_BAN_CONFIRM'] = '[MISSING TEXT: ADMIN_BAN_CONFIRM]'

OVERRIDES['ADMIN_BAN_FAILED'] = '[MISSING TEXT: ADMIN_BAN_FAILED]'

OVERRIDES['ADMIN_BAN_SUCCESS'] = '[MISSING TEXT: ADMIN_BAN_SUCCESS]'

OVERRIDES['ADMIN_DELETE_DEVICE_CONFIRM'] = '[MISSING TEXT: ADMIN_DELETE_DEVICE_CONFIRM]'

OVERRIDES['ADMIN_DELETE_DEVICE_ERROR'] = '[MISSING TEXT: ADMIN_DELETE_DEVICE_ERROR]'

OVERRIDES['ADMIN_DELETE_DEVICE_FAILED'] = '[MISSING TEXT: ADMIN_DELETE_DEVICE_FAILED]'

OVERRIDES['ADMIN_DELETE_DEVICE_SUCCESS'] = '[MISSING TEXT: ADMIN_DELETE_DEVICE_SUCCESS]'

OVERRIDES['ADMIN_MANUAL_GRANT_USER_BANNED'] = '[MISSING TEXT: ADMIN_MANUAL_GRANT_USER_BANNED]'

OVERRIDES['ADMIN_MANUAL_GRANT_USER_DELETED'] = '[MISSING TEXT: ADMIN_MANUAL_GRANT_USER_DELETED]'

OVERRIDES['ADMIN_SERVER_ADDED'] = '[MISSING TEXT: ADMIN_SERVER_ADDED]'

OVERRIDES['ADMIN_SERVER_CARD'] = '[MISSING TEXT: ADMIN_SERVER_CARD]'

OVERRIDES['ADMIN_SERVER_CHECKING'] = '[MISSING TEXT: ADMIN_SERVER_CHECKING]'

OVERRIDES['ADMIN_SERVER_DELETE_CONFIRM'] = '[MISSING TEXT: ADMIN_SERVER_DELETE_CONFIRM]'

OVERRIDES['ADMIN_SERVER_EDIT_KEY_PROMPT'] = '[MISSING TEXT: ADMIN_SERVER_EDIT_KEY_PROMPT]'

OVERRIDES['ADMIN_SERVER_EDIT_MAX_CLIENTS_PROMPT'] = '[MISSING TEXT: ADMIN_SERVER_EDIT_MAX_CLIENTS_PROMPT]'

OVERRIDES['ADMIN_SERVER_EDIT_URL_PROMPT'] = '[MISSING TEXT: ADMIN_SERVER_EDIT_URL_PROMPT]'

OVERRIDES['ADMIN_SERVER_FLAG_PROMPT'] = '[MISSING TEXT: ADMIN_SERVER_FLAG_PROMPT]'

OVERRIDES['ADMIN_SERVER_FLAG_PROMPT_EDIT'] = '[MISSING TEXT: ADMIN_SERVER_FLAG_PROMPT_EDIT]'

OVERRIDES['ADMIN_SERVER_FLAG_TOO_LONG'] = '[MISSING TEXT: ADMIN_SERVER_FLAG_TOO_LONG]'

OVERRIDES['ADMIN_SERVER_FLAG_UPDATED'] = '[MISSING TEXT: ADMIN_SERVER_FLAG_UPDATED]'

OVERRIDES['ADMIN_SERVER_KEY_PROMPT'] = '[MISSING TEXT: ADMIN_SERVER_KEY_PROMPT]'

OVERRIDES['ADMIN_SERVER_KEY_UPDATED'] = '[MISSING TEXT: ADMIN_SERVER_KEY_UPDATED]'

OVERRIDES['ADMIN_SERVER_MAX_CLIENTS_UPDATED'] = '[MISSING TEXT: ADMIN_SERVER_MAX_CLIENTS_UPDATED]'

OVERRIDES['ADMIN_SERVER_MAX_CLIENTS_WARNING'] = '[MISSING TEXT: ADMIN_SERVER_MAX_CLIENTS_WARNING]'

OVERRIDES['ADMIN_SERVER_NAME_PROMPT'] = '[MISSING TEXT: ADMIN_SERVER_NAME_PROMPT]'

OVERRIDES['ADMIN_SERVER_RENAMED'] = '[MISSING TEXT: ADMIN_SERVER_RENAMED]'

OVERRIDES['ADMIN_SERVER_RENAME_PROMPT'] = '[MISSING TEXT: ADMIN_SERVER_RENAME_PROMPT]'

OVERRIDES['ADMIN_SERVER_STATE_DISABLED'] = '[MISSING TEXT: ADMIN_SERVER_STATE_DISABLED]'

OVERRIDES['ADMIN_SERVER_STATE_ENABLED'] = '[MISSING TEXT: ADMIN_SERVER_STATE_ENABLED]'

OVERRIDES['ADMIN_SERVER_TOGGLE_DISABLE_CONFIRM'] = '[MISSING TEXT: ADMIN_SERVER_TOGGLE_DISABLE_CONFIRM]'

OVERRIDES['ADMIN_SERVER_TOGGLE_ENABLE_CONFIRM'] = '[MISSING TEXT: ADMIN_SERVER_TOGGLE_ENABLE_CONFIRM]'

OVERRIDES['ADMIN_SERVER_TOGGLE_SUCCESS'] = '[MISSING TEXT: ADMIN_SERVER_TOGGLE_SUCCESS]'

OVERRIDES['ADMIN_SERVER_URL_UPDATED'] = '[MISSING TEXT: ADMIN_SERVER_URL_UPDATED]'

OVERRIDES['ADMIN_SUBSCRIPTION_HEADER'] = '[MISSING TEXT: ADMIN_SUBSCRIPTION_HEADER]'

OVERRIDES['ADMIN_SUB_CHANGE_FAILED'] = '[MISSING TEXT: ADMIN_SUB_CHANGE_FAILED]'

OVERRIDES['ADMIN_SUB_CHANGE_TARIFF_HEADER'] = '[MISSING TEXT: ADMIN_SUB_CHANGE_TARIFF_HEADER]'

OVERRIDES['ADMIN_SUB_CONFIRM_EXTEND'] = '[MISSING TEXT: ADMIN_SUB_CONFIRM_EXTEND]'

OVERRIDES['ADMIN_SUB_CONFIRM_GRANT'] = '[MISSING TEXT: ADMIN_SUB_CONFIRM_GRANT]'

OVERRIDES['ADMIN_SUB_CONFIRM_REDUCE'] = '[MISSING TEXT: ADMIN_SUB_CONFIRM_REDUCE]'

OVERRIDES['ADMIN_SUB_CONFIRM_TARIFF'] = '[MISSING TEXT: ADMIN_SUB_CONFIRM_TARIFF]'

OVERRIDES['ADMIN_SUB_DOWNGRADE_BLOCKED'] = '[MISSING TEXT: ADMIN_SUB_DOWNGRADE_BLOCKED]'

OVERRIDES['ADMIN_SUB_EXTEND_FAILED'] = '[MISSING TEXT: ADMIN_SUB_EXTEND_FAILED]'

OVERRIDES['ADMIN_SUB_EXTEND_HEADER'] = '[MISSING TEXT: ADMIN_SUB_EXTEND_HEADER]'

OVERRIDES['ADMIN_SUB_EXTEND_PROMPT'] = '[MISSING TEXT: ADMIN_SUB_EXTEND_PROMPT]'

OVERRIDES['ADMIN_SUB_EXTEND_SUCCESS'] = '[MISSING TEXT: ADMIN_SUB_EXTEND_SUCCESS]'

OVERRIDES['ADMIN_SUB_GRANT_CUSTOM_PROMPT'] = '[MISSING TEXT: ADMIN_SUB_GRANT_CUSTOM_PROMPT]'

OVERRIDES['ADMIN_SUB_GRANT_DAYS_HEADER'] = '[MISSING TEXT: ADMIN_SUB_GRANT_DAYS_HEADER]'

OVERRIDES['ADMIN_SUB_GRANT_FAILED'] = '[MISSING TEXT: ADMIN_SUB_GRANT_FAILED]'

OVERRIDES['ADMIN_SUB_GRANT_HEADER'] = '[MISSING TEXT: ADMIN_SUB_GRANT_HEADER]'

OVERRIDES['ADMIN_SUB_GRANT_SUCCESS'] = '[MISSING TEXT: ADMIN_SUB_GRANT_SUCCESS]'

OVERRIDES['ADMIN_SUB_GROUP_NOT_FOUND'] = '[MISSING TEXT: ADMIN_SUB_GROUP_NOT_FOUND]'

OVERRIDES['ADMIN_SUB_NO_SUBSCRIPTION'] = '[MISSING TEXT: ADMIN_SUB_NO_SUBSCRIPTION]'

OVERRIDES['ADMIN_SUB_PERMANENT_LABEL'] = '[MISSING TEXT: ADMIN_SUB_PERMANENT_LABEL]'

OVERRIDES['ADMIN_SUB_REDUCED'] = '[MISSING TEXT: ADMIN_SUB_REDUCED]'

OVERRIDES['ADMIN_SUB_REDUCE_FAILED'] = '[MISSING TEXT: ADMIN_SUB_REDUCE_FAILED]'

OVERRIDES['ADMIN_SUB_REDUCE_PROMPT'] = '[MISSING TEXT: ADMIN_SUB_REDUCE_PROMPT]'

OVERRIDES['ADMIN_SUB_STATUS_ACTIVE'] = '[MISSING TEXT: ADMIN_SUB_STATUS_ACTIVE]'

OVERRIDES['ADMIN_SUB_STATUS_INACTIVE'] = '[MISSING TEXT: ADMIN_SUB_STATUS_INACTIVE]'

OVERRIDES['ADMIN_SUB_STATUS_NONE'] = '[MISSING TEXT: ADMIN_SUB_STATUS_NONE]'

OVERRIDES['ADMIN_SUB_TARIFF_ALREADY_SELECTED'] = '[MISSING TEXT: ADMIN_SUB_TARIFF_ALREADY_SELECTED]'

OVERRIDES['ADMIN_SUB_TARIFF_CHANGED'] = '[MISSING TEXT: ADMIN_SUB_TARIFF_CHANGED]'

OVERRIDES['ADMIN_TARIFF_EDIT_RUB_PROMPT'] = '[MISSING TEXT: ADMIN_TARIFF_EDIT_RUB_PROMPT]'

OVERRIDES['ADMIN_TARIFF_EDIT_RUB_SUCCESS'] = '[MISSING TEXT: ADMIN_TARIFF_EDIT_RUB_SUCCESS]'

OVERRIDES['ADMIN_TARIFF_TOGGLE_BLOCKED_PENDING'] = '[MISSING TEXT: ADMIN_TARIFF_TOGGLE_BLOCKED_PENDING]'

OVERRIDES['ADMIN_TARIFF_TOGGLE_SUCCESS_DISABLED'] = '[MISSING TEXT: ADMIN_TARIFF_TOGGLE_SUCCESS_DISABLED]'

OVERRIDES['ADMIN_TARIFF_TOGGLE_SUCCESS_ENABLED'] = '[MISSING TEXT: ADMIN_TARIFF_TOGGLE_SUCCESS_ENABLED]'

OVERRIDES['ADMIN_UNBAN_CONFIRM'] = '[MISSING TEXT: ADMIN_UNBAN_CONFIRM]'

OVERRIDES['ADMIN_USER_DEVICES_EMPTY'] = '[MISSING TEXT: ADMIN_USER_DEVICES_EMPTY]'

OVERRIDES['ADMIN_USER_DEVICES_HEADER'] = '[MISSING TEXT: ADMIN_USER_DEVICES_HEADER]'

OVERRIDES['ALERT_CRITICAL_BOT_ERROR'] = '[MISSING TEXT: ALERT_CRITICAL_BOT_ERROR]'

OVERRIDES['ERROR_SERVER_DUPLICATE_URL'] = '[MISSING TEXT: ERROR_SERVER_DUPLICATE_URL]'

OVERRIDES['PAYMENT_STATUS_NAMES'] = {'completed': 'Выполнен', 'cancelled': 'Отменен', 'failed': 'Ошибка', 'refunded': 'Возврат', 'requires_manual_review': 'Ручная проверка', 'pending': 'Ожидание', 'paid_processing': 'Обработка'}
