from datetime import datetime, timezone

from config.constants import AMNEZIA_PROTOCOL, MAX_RAW_CONFIG_BYTES

PERMANENT_SUBSCRIPTION_DAYS = 36500
PERMANENT_END_DATE = datetime(2100, 1, 1, tzinfo=timezone.utc)
TELEGRAM_MESSAGE_LIMIT = 4096
TRAFFIC_SYNC_INTERVAL = 900
NOTIFICATION_INTERVAL = 1800
# P1 #5: Reduced from 3600s (1 hour) to 300s (5 minutes)
# Users waited too long when webhook was lost
STALE_PAYMENT_THRESHOLD = 300
WORKER_ERROR_SLEEP_INTERVAL = 60
API_CONCURRENCY_LIMIT = 20
API_RETRY_COUNT = 2
API_TIMEOUT = 15
HUB_CACHE_MAX_SIZE = 10000
HUB_CACHE_TTL = 43200
USER_CONTEXT_CACHE_MAX_SIZE = 2000
USER_CONTEXT_CACHE_TTL = 15.0
DEVICE_DAILY_LIMIT = 25
SELF_HEALING_MAX_PER_CYCLE = 50
GRACE_PERIOD_HOURS = 24

__all__ = [
    "AMNEZIA_PROTOCOL",
    "API_CONCURRENCY_LIMIT",
    "API_RETRY_COUNT",
    "API_TIMEOUT",
    "DEVICE_DAILY_LIMIT",
    "GRACE_PERIOD_HOURS",
    "HUB_CACHE_MAX_SIZE",
    "HUB_CACHE_TTL",
    "MAX_RAW_CONFIG_BYTES",
    "NOTIFICATION_INTERVAL",
    "PERMANENT_END_DATE",
    "PERMANENT_SUBSCRIPTION_DAYS",
    "SELF_HEALING_MAX_PER_CYCLE",
    "STALE_PAYMENT_THRESHOLD",
    "TELEGRAM_MESSAGE_LIMIT",
    "TRAFFIC_SYNC_INTERVAL",
    "USER_CONTEXT_CACHE_MAX_SIZE",
    "USER_CONTEXT_CACHE_TTL",
    "WORKER_ERROR_SLEEP_INTERVAL",
]