"""Domain copy catalogue for: bot/texts_data/admin/common.py"""

TEXTS = {
    'UI_COMMON_AKTIVEN_110': '🟢 <b>Активен</b>',
    'UI_COMMON_AVTOMATICHESKI_OTKLYUCHEN_113': '🔴 <b>Автоматически отключён</b>',
    'UI_COMMON_PRICHINA_API_NEDOSTUPEN_NESTAB_117': '• Причина: <b>API недоступен / нестабильное соединение</b>\n',
    'UI_COMMON_OTKLYUCHEN_118': '• Отключён: <code>{disabled_at_str}</code>\n',
    'UI_COMMON_POSLEDNIY_OTKLIK_119': '• Последний отклик: <code>{last_check_str}</code>\n',
    'UI_COMMON_OTKLYUCHEN_VRUCHNUYU_122': '🔴 <b>Отключён вручную</b>',
    'UI_COMMON_SERVERY_128': '🖥 Серверы',
    'UI_COMMON_KARTOCHKA_VPN_SERVERA_ID_132': '🖥 <b>Карточка сервера {flag} {safe_server_name}</b> (ID: {server_id})\n\n',
    'UI_COMMON_STATUS_V_BOTE_133': '• Статус в боте: {status_line}\n',
    'UI_COMMON_PROTOKOL_135': '• Протокол: <code>{safe_server_protocol}</code>\n',
    'UI_COMMON_ZAPOLNENNOST_SLOTOV_136': '• Заполненность слотов: <b>{used_clients} / {max_clients}</b>\n',
    'UI_COMMON_REZULTAT_PROVERKI_SVYAZI_141': '\n⚡ <b>Результат проверки связи:</b>\n{ping_result}\n',
    'UI_COMMON_POLZOVATELI_164': '👥 Пользователи',
    'UI_COMMON_FILTR_164': 'Фильтр: {f_name}',
    'UI_COMMON_UPRAVLENIE_POLZOVATELYAMI_STR__168': '👥 <b>Управление пользователями</b> (Стр. {page}/{total_pages}, всего: {total})\n\n',
    'UI_COMMON_VSE_174': 'Все',
    'UI_COMMON_NOVYE_7D_175': '🆕 Новые (7д)',
    'UI_COMMON_3_DNEY_176': '⏳ < 3 дней',
    'UI_COMMON_AKTIVNYE_177': '⚡ Активные',
    'UI_COMMON_BEZ_PODPISKI_178': '🔴 Без подписки',
    'UI_COMMON_ZABANENNYE_179': '🚫 Забаненные',
    'UI_COMMON_PO_VPN_SERVERAM_ACTIVE_189': '• 🖥 По серверам •',
    'UI_COMMON_PO_VPN_SERVERAM_189': '🖥 По серверам',
    'UI_COMMON_PO_TARIFAM_ACTIVE_190': '• 💎 По тарифам •',
    'UI_COMMON_PO_TARIFAM_190': '💎 По тарифам',
    'UI_COMMON_POLZOVATELI_NE_NAYDENY_196': '<i>Пользователи не найдены.</i>',
    'UI_COMMON_BAN_206': ' [БАН]',
    'UI_COMMON_BLOK_BOTA_206': ' [Блок бота]',
    'UI_COMMON_USTR_218': '{status}{ban} {username} | {days} | {profiles_count} устр.',
    'UI_COMMON_NAZAD_229': '◀️ Назад',
    'UI_COMMON_VPERED_236': 'Вперед ▶️',
    'UI_COMMON_POISK_PO_USERNAME_ID_242': '🔍 Поиск по @username / ID',
    'UI_COMMON_V_ADMIN_MENYU_247': '🔙 В админ-меню',
    'UI_COMMON_NE_AKTIVIROVAN_265': 'Не активирован',
    'UI_COMMON_DO_USTR_269': '{tariff_name} (до {tariff_device_limit} устр.)',
    'UI_COMMON_DO_USTR_272': '{t_name} (до {user_device_limit} устр.)',
    'UI_COMMON_PRYAMOY_PEREKHOD_274': 'Прямой переход',
}
