"""Domain copy catalogue for: bot/texts_data/admin/purchases.py"""

TEXTS = {
    'UI_PURCHASES_POKUPKI_39': '🛒 Покупки',
    'UI_PURCHASES_STR_39': 'Стр. {page}/{total_pages}',
    'UI_PURCHASES_LOGI_POKUPOK_POLZOVATELEY_STR__42': '🛒 <b>Логи покупок пользователей</b> (Стр. {page}/{total_pages}, всего: {total})\n\n',
    'UI_PURCHASES_POKUPKI_NE_NAYDENY_48': '<i>Покупки не найдены.</i>',
    'UI_PURCHASES_0_BONUS_52': '0 ₽ (Бонус)',
    'UI_PURCHASES_DN_USTR_55': '   💎 {safe_entry_tariff_name} ({entry_duration_days} дн., {entry_device_limit} устр.) — <b>{amount_str}</b>\n',
    'UI_PURCHASES_NAZAD_71': '◀️ Назад',
    'UI_PURCHASES_VPERED_78': 'Вперед ▶️',
    'UI_PURCHASES_K_PLATEZHAM_83': '💳 К платежам',
    'UI_PURCHASES_V_ADMIN_MENYU_84': '🔙 В админ-меню',
    'UI_PURCHASES_ZAPIS_POKUPKI_NE_NAYDENA_146': 'Запись покупки не найдена',
    'UI_PURCHASES_POKUPKA_NE_NAYDENA_152': 'Покупка не найдена',
    'UI_PURCHASES_POKUPKI_158': '🛒 Покупки',
    'UI_PURCHASES_DETALI_158': 'Детали #{entry_numeric_id}',
    'UI_PURCHASES_0_BONUS_VYDACHA_159': '0 ₽ (Бонус/Выдача)',
    'UI_PURCHASES_DETALI_POKUPKI_TRANZAKTSII_164': '🛒 <b>Детали покупки / транзакции #{entry_numeric_id}</b>\n\n',
    'UI_PURCHASES_POLZOVATEL_TELEGRAM_ID_165': '👤 <b>Пользователь:</b> {safe_entry_user_label} (Telegram ID: <code>{entry_telegram_id}</code>)\n',
    'UI_PURCHASES_TARIF_166': '💎 <b>Тариф:</b> {safe_entry_tariff_name}\n',
    'UI_PURCHASES_LIMIT_USTROYSTV_SHT_167': '📱 <b>Лимит устройств:</b> {entry_device_limit} шт.\n',
    'UI_PURCHASES_DLITELNOST_DNEY_168': '⏳ <b>Длительность:</b> {entry_duration_days} дней\n',
    'UI_PURCHASES_SUMMA_169': '💳 <b>Сумма:</b> <b>{amount_str}</b>\n',
    'UI_PURCHASES_TIP_OPERATSII_170': '⚙️ <b>Тип операции:</b> {safe_entry_operation_title}\n',
    'UI_PURCHASES_DATA_I_VREMYA_171': '🕒 <b>Дата и время:</b> {dt_str}\n',
    'UI_PURCHASES_KARTOCHKA_POLZOVATELYA_178': '👤 Карточка пользователя',
    'UI_PURCHASES_K_SPISKU_POKUPOK_181': '🛒 К списку покупок',
    'UI_PURCHASES_V_ADMIN_MENYU_182': '🔙 В админ-меню',
}
