"""Domain copy catalogue for: admin/queues.py"""

TEXTS = {
    'ADMIN_QUEUE_CARD_ERROR': 'Error code: {error_code}',
    'ADMIN_QUEUE_CARD_ID': 'ID: <code>{operation_id}</code>',
    'ADMIN_QUEUE_CARD_LEASE': 'Lease: {lease}',
    'ADMIN_QUEUE_CARD_LOCK': 'Lock timestamp: {locked_at}',
    'ADMIN_QUEUE_CARD_PAYMENT': 'Payment ID: {payment_id}',
    'ADMIN_QUEUE_NAME': '<b>{name}</b>',
    'ADMIN_QUEUE_PROVIDER_LABEL': 'Provider operations',
    'ADMIN_QUEUE_PROVIDER_SHORT': 'Provider',
    'ADMIN_QUEUE_REFUNDS_SHORT': 'Refunds',
    'ADMIN_QUEUE_RETRY_CONFIRMATION': """{card}

⚠️ Операция может быть обработана повторно.""",
    'ADMIN_QUEUE_WEBHOOK_LABEL': 'Webhook inbox',
    'ADMIN_QUEUE_WEBHOOK_SHORT': 'Webhook',
    'QUEUE_HEALTH_CODE_FRAGMENT': ' code={code}',
    'QUEUE_HEALTH_EXAMPLE': '<code>id={operation_id}{payment} type={operation_type} status={status} attempts={attempts}/{max_attempts} age={age}s{code}</code>',
    'QUEUE_HEALTH_PAYMENT_FRAGMENT': ' payment={payment_id}',
    'QUEUE_HEALTH_PROBLEM_DEAD': 'dead={count} oldest={age}s',
    'QUEUE_HEALTH_PROBLEM_OVERDUE': 'overdue={count} oldest={age}s',
    'QUEUE_HEALTH_PROBLEM_STALE': 'stale_processing={count} oldest={age}s',
    'QUEUE_OPERATION_NOT_FOUND': 'Операция не найдена',
    'QUEUE_RETRY_AVAILABLE': 'доступен',
    'QUEUE_RETRY_UNAVAILABLE': 'недоступен',
    'RUNTIME_BOT_HANDLERS_ADMIN_PAYMENT_QUEUES_L105_1': 'pending={value_0} · retry={value_1} · due={value_2} · overdue={value_3}',
    'RUNTIME_BOT_HANDLERS_ADMIN_PAYMENT_QUEUES_L106_1': 'processing={value_0} · stale={value_1} · dead={value_2}',
    'RUNTIME_BOT_HANDLERS_ADMIN_PAYMENT_QUEUES_L107_1': 'Старейшая проблема: {value_0}',
    'RUNTIME_BOT_HANDLERS_ADMIN_PAYMENT_QUEUES_L126_1': '🧰 <b>{value_0}</b>',
    'RUNTIME_BOT_HANDLERS_ADMIN_PAYMENT_QUEUES_L127_1': 'Проблемные операции · стр. {value_0}/{value_1} · всего {value_2}',
    'RUNTIME_BOT_HANDLERS_ADMIN_PAYMENT_QUEUES_L132_1': 'Проблемных операций нет.',
    'RUNTIME_BOT_HANDLERS_ADMIN_PAYMENT_QUEUES_L135_1': '#{value_0} · {value_1} · {value_2} · {value_3}/{value_4} · error={value_5} · возраст {value_6}',
    'RUNTIME_BOT_HANDLERS_ADMIN_PAYMENT_QUEUES_L140_1': '#{value_0} · {value_1} · {value_2}',
    'RUNTIME_BOT_HANDLERS_ADMIN_PAYMENT_QUEUES_L155_1': '🧰 <b>{value_0}</b>',
    'RUNTIME_BOT_HANDLERS_ADMIN_PAYMENT_QUEUES_L158_1': 'Тип: {value_0}',
    'RUNTIME_BOT_HANDLERS_ADMIN_PAYMENT_QUEUES_L159_1': 'Статус: {value_0}',
    'RUNTIME_BOT_HANDLERS_ADMIN_PAYMENT_QUEUES_L160_1': 'Попытки: {value_0}/{value_1}',
    'RUNTIME_BOT_HANDLERS_ADMIN_PAYMENT_QUEUES_L162_1': 'Создано: {value_0}',
    'RUNTIME_BOT_HANDLERS_ADMIN_PAYMENT_QUEUES_L163_1': 'Обновлено: {value_0}',
    'RUNTIME_BOT_HANDLERS_ADMIN_PAYMENT_QUEUES_L164_1': 'Завершено/обработано: {value_0}',
    'RUNTIME_BOT_HANDLERS_ADMIN_PAYMENT_QUEUES_L167_1': 'Ручной retry: {value_0}',
    'RUNTIME_BOT_HANDLERS_ADMIN_PAYMENT_QUEUES_L231_1': 'Операция не найдена',
    'RUNTIME_BOT_HANDLERS_ADMIN_PAYMENT_QUEUES_L358_1': 'Операция поставлена в retry. Исполнение выполнит фоновый worker.',
    'RUNTIME_BOT_HANDLERS_ADMIN_PAYMENT_QUEUES_L359_1': 'Retry отклонён: {value_0}',
    'RUNTIME_BOT_HANDLERS_ADMIN_PAYMENT_QUEUES_L360_1': 'Операция не найдена',
    'RUNTIME_BOT_HANDLERS_ADMIN_PAYMENT_QUEUES_L361_1': 'Состояние уже изменилось',
    'RUNTIME_BOT_HANDLERS_ADMIN_PAYMENT_QUEUES_L365_1': 'Состояние уже изменилось',
    'RUNTIME_BOT_HANDLERS_ADMIN_PAYMENT_QUEUES_L383_1': 'Отменено',
    'RUNTIME_BOT_HANDLERS_ADMIN_PAYMENT_QUEUES_L57_1': '—',
    'RUNTIME_BOT_HANDLERS_ADMIN_PAYMENT_QUEUES_L59_1': '{value_0}д',
    'RUNTIME_BOT_HANDLERS_ADMIN_PAYMENT_QUEUES_L61_1': '{value_0}ч',
    'RUNTIME_BOT_HANDLERS_ADMIN_PAYMENT_QUEUES_L63_1': '{value_0}м',
    'RUNTIME_BOT_HANDLERS_ADMIN_PAYMENT_QUEUES_L64_1': '{value_0}с',
    'UI_BOT_HANDLERS_ADMIN_PAYMENT_QUEUES_L144_1': '⬅️',
    'UI_BOT_HANDLERS_ADMIN_PAYMENT_QUEUES_L146_1': '➡️',
    'UI_BOT_HANDLERS_ADMIN_PAYMENT_QUEUES_L147_1': '← Диагностика',
    'UI_BOT_HANDLERS_ADMIN_PAYMENT_QUEUES_L181_1': 'Подготовить retry',
    'UI_BOT_HANDLERS_ADMIN_PAYMENT_QUEUES_L184_1': '← К очереди',
    'UI_BOT_HANDLERS_ADMIN_PAYMENT_QUEUES_L205_1': 'Некорректный запрос',
    'UI_BOT_HANDLERS_ADMIN_PAYMENT_QUEUES_L209_1': 'Некорректная страница',
    'UI_BOT_HANDLERS_ADMIN_PAYMENT_QUEUES_L213_1': 'Некорректная страница',
    'UI_BOT_HANDLERS_ADMIN_PAYMENT_QUEUES_L228_1': 'Некорректный ID',
    'UI_BOT_HANDLERS_ADMIN_PAYMENT_QUEUES_L246_1': 'Некорректный ID',
    'UI_BOT_HANDLERS_ADMIN_PAYMENT_QUEUES_L250_1': 'Состояние уже изменилось',
    'UI_BOT_HANDLERS_ADMIN_PAYMENT_QUEUES_L260_1': 'Укажите причину ручного retry (3–200 символов).',
    'UI_BOT_HANDLERS_ADMIN_PAYMENT_QUEUES_L280_1': 'Подтверждение устарело.',
    'UI_BOT_HANDLERS_ADMIN_PAYMENT_QUEUES_L283_1': 'Причина обязательна и должна содержать 3–200 символов.',
    'UI_BOT_HANDLERS_ADMIN_PAYMENT_QUEUES_L288_1': 'Состояние уже изменилось',
    'UI_BOT_HANDLERS_ADMIN_PAYMENT_QUEUES_L295_1': 'Подтвердить retry',
    'UI_BOT_HANDLERS_ADMIN_PAYMENT_QUEUES_L298_1': 'Отмена',
    'UI_BOT_HANDLERS_ADMIN_PAYMENT_QUEUES_L334_1': 'Подтверждение устарело',
    'UI_BOT_HANDLERS_ADMIN_PAYMENT_QUEUES_L71_1': 'Открыть {value_0}',
    'UI_BOT_HANDLERS_ADMIN_PAYMENT_QUEUES_L74_1': '🔄 Обновить',
    'UI_BOT_HANDLERS_ADMIN_PAYMENT_QUEUES_L75_1': '← В админку',
}
